#!/usr/bin/env bash
# /opt/data/scripts/cred-rotation-reminder.sh
# Lembrete mensal de rotação de credenciais
# Roda no dia 1 de cada mês às 09:00 via cron

set -euo pipefail

echo "🔐 === LEMBRETE MENSAL: ROTAÇÃO DE CREDENCIAIS ==="
echo "Data: $(date)"
echo ""

echo "Credenciais a revisar/rotacionar:"
echo ""
echo "1️⃣  TELEGRAM_BOT_TOKEN"
echo "   - Painel: https://my.telegram.org/apps"
echo "   - Revogar token antigo → gerar novo → atualizar /opt/data/.env"
echo "   - Reiniciar gateway: hermes gateway restart"
echo ""
echo "2️⃣  OPENROUTER_API_KEY"
echo "   - Painel: https://openrouter.ai/keys"
echo "   - Revogar key antiga → criar nova → atualizar .env"
echo ""
echo "3️⃣  GROQ_API_KEY"
echo "   - Painel: https://console.groq.com/keys"
echo ""
echo "4️⃣  OPENAI_API_KEY"
echo "   - Painel: https://platform.openai.com/api-keys"
echo ""
echo "5️⃣  GITHUB_TOKEN"
echo "   - Painel: https://github.com/settings/tokens"
echo ""
echo "6️⃣  HF_TOKEN (Hugging Face)"
echo "   - Painel: https://huggingface.co/settings/tokens"
echo ""
echo "7️⃣  TAVILY_API_KEY"
echo "   - Painel: https://tavily.com/dashboard"
echo ""
echo "8️⃣  Google OAuth (client_secret.json + google_token.json)"
echo "   - Console: https://console.cloud.google.com/apis/credentials"
echo "   - Rotacionar client secret se suspeitar vazamento"
echo "   - Re-autenticar no Hermes se rotacionar"
echo ""
echo "9️⃣  SPOTIFY (auth_spotify.json)"
echo "   - Dashboard: https://developer.spotify.com/dashboard"
echo ""
echo "🔟  RAFT_PROFILE (se usar Raft)"
echo "   - https://api.raft.build → regenerate credential"
echo ""
echo "---"
echo "✅ Após rotacionar QUALQUER credencial:"
echo "   1. Edite /opt/data/.env ou arquivo correspondente"
echo "   2. Reinicie o gateway: hermes gateway restart"
echo "   3. Teste: /opt/hermes/bin/hermes chat -q 'teste'"
echo ""
echo "📁 Backup pré-rotação salvo em: /opt/data/backups/"
echo "   (script backup-hermes-selective.sh roda diariamente às 03:00)"
echo ""
echo "=== FIM DO LEMBRETE ==="